image: "jethubjhaos/{arch}-builder"
shadow_repository: "ghcr.io/jethub-homeassistant"
build_from:
  aarch64: "ghcr.io/jethub-homeassistant/aarch64-base:3.16"
  armv7: "ghcr.io/jethub-homeassistant/armv7-base:3.16"
  armhf: "ghcr.io/jethub-homeassistant/armhf-base:3.16"
  amd64: "ghcr.io/jethub-homeassistant/amd64-base:3.16"
  i386: "ghcr.io/jethub-homeassistant/i386-base:3.16"
codenotary:
  signer: vb@jethome.ru
  base_image: vb@jethome.ru
args:
  CAS_VERSION: "1.0.1"
  YQ_VERSION: "v4.13.2"
labels:
  io.hass.type: builder
  org.opencontainers.image.title: "Home Assistant Builder"
  org.opencontainers.image.description: "Container-based build system for Home Assistant"
  org.opencontainers.image.source: "https://github.com/jethub-homeassistant/builder"
  org.opencontainers.image.authors: "The Home Assistant Authors & JetHome mods"
  org.opencontainers.image.url: "https://www.home-assistant.io/"
  org.opencontainers.image.documentation: "https://developers.home-assistant.io/"
  org.opencontainers.image.licenses: "Apache License 2.0"
